### PR TITLE
[terra-application] Added mutation observer shim to better support inert in IE10.

### LINKED ISSUE #101: Add the mutation observer shim wherever we are including the inert polyfill
# Bug Report

## Description

Because we support IE10, we need to add the mutation observer shim wherever we are including the inert polyfill. This includes:

https://github.com/cerner/terra-application/blob/9ac75245410caa2d6d59f87ead3650daab0e7033/src/application-status-overlay/ApplicationStatusOverlayProvider.jsx#L76

and

https://github.com/cerner/terra-application/blob/39f142352f2233924235bbbd58c00ba34b7d0122/src/application-base/private/initializeInert.js#L30

We should mimic what we're doing here:

https://github.com/cerner/terra-framework/blob/4880772b8b92bb05f99ef3f3084a8d1e4c389bdc/packages/terra-abstract-modal/src/AbstractModal.jsx#L5

### PR DESCRIPTION
**Pull request by saket2403**
### Summary
Added mutation observer shim and node contains polyfill to better support inert polyfill in IE10.

Closes #101 

### Deployment Link

https://terra-applic-.herokuapp.com/

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

File: src/application-base/private/_contains-polyfill.js [hunk 1]
```diff
@@ -0,0 +1,19 @@
+// Source: https://github.com/Financial-Times/polyfill-service/pull/183/files
```
Comment (ShettyAkarsh) [inline src/application-base/private/_contains-polyfill.js]: can we have these same files moved to single common folder for entire terra-application package

Comment (saket2403) [reply src/application-base/private/_contains-polyfill.js]: Done 8e05b49

File: src/utils/_contains-polyfill.js [hunk 2]
```diff
@@ -0,0 +1,19 @@
+// Source: https://github.com/Financial-Times/polyfill-service/pull/183/files
+// Needed for IE11 and IE10
+if (!Node.prototype.contains) {
+  Node.prototype.contains = function contains(node) {
+    /* eslint-disable-next-line prefer-rest-params */
+    if (!(0 in arguments)) {
+      throw new TypeError('1 argument is required');
+    }
+    /* eslint-disable no-cond-assign */
```
Comment (emilyrohrbough) [inline src/utils/_contains-polyfill.js]: Is this disabled rule needed?

**Review by emilyrohrbough — COMMENTED** [review]
Should these polyfill be included at the webpack configuration level? Seems like contains and matches should be provided in our builds already

File: src/utils/_contains-polyfill.js [hunk 3]
```diff
@@ -0,0 +1,19 @@
+// Source: https://github.com/Financial-Times/polyfill-service/pull/183/files
```
Comment (ShettyAkarsh) [inline src/utils/_contains-polyfill.js]: can we have these files in polyfills folder under utils ?

File: src/application-status-overlay/ApplicationStatusOverlayProvider.jsx [hunk 4]
```diff
@@ -6,6 +6,9 @@ import StatusView from 'terra-status-view';
 import ThemeContext from 'terra-theme-context';
 import ApplicationStatusOverlayContext from './ApplicationStatusOverlayContext';
 import styles from './ApplicationStatusOverlayProvider.module.scss';
+import 'mutationobserver-shim';
```
Comment (tbiethman) [inline src/application-status-overlay/ApplicationStatusOverlayProvider.jsx]: With inert being initialized automatically with the ApplicationBase import, these imports (and the `require` on line 79) no longer need to be included here.

**Review by tbiethman — APPROVED** [review]

File: package.json [hunk 5]
```diff
@@ -105,6 +105,7 @@
     "@cerner/terra-docs": "^1.0.0",
     "classnames": "^2.2.5",
     "eventemitter3": "^4.0.4",
+    "mutationobserver-shim": "0.3.3",
```
Comment (benbcai) [inline package.json:108]: Is there a reason why using 0.3.3 instead of the latest 0.3.7?

Comment (yuderekyu) [reply package.json:108]: to add to this, does anyone remember why we lock this down? is it because there still hasn't been a major release?

File: src/application-status-overlay/ApplicationStatusOverlayProvider.jsx (hunk 4 above)
Comment (ryanthemanuel) [reply src/application-status-overlay/ApplicationStatusOverlayProvider.jsx]: Let's go ahead and remove it from this file since it's not needed.

File: src/utils/_contains-polyfill.js (hunk 2 above)
Comment (saket2403) [reply src/utils/_contains-polyfill.js]: Yes

File: src/utils/_contains-polyfill.js (hunk 3 above)
Comment (saket2403) [reply src/utils/_contains-polyfill.js]: Moved

File: src/application-status-overlay/ApplicationStatusOverlayProvider.jsx (hunk 4 above)
Comment (saket2403) [reply src/application-status-overlay/ApplicationStatusOverlayProvider.jsx]: Removed 235f298

**Review by benbcai — APPROVED** [review]

**Review by emilyrohrbough — APPROVED** [review]
